sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jevgenijkersov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jevgenijkersov/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-117307189725"
  bucket_path: "docker-react"
  on:
    branch: "master"
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secret: "$AWS_SECRET_KEY"